# Generated by Django 5.0.1 on 2024-04-29 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_login', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Proflle',
            new_name='Profile',
        ),
    ]
